name: Security Scanning

on:
  push:
    branches: ["dev", "main", "master"]
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit semgrep

      - name: Dependency vulnerability scan
        uses: snyk/actions/python@v1
        with:
          args: --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Bandit
        run: bandit -r powerdnsadmin -ll

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1

      - name: Build docker image
        uses: docker/build-push-action@v4
        with:
          context: ./
          load: true

      - name: Trivy container scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: powerdnsadmin:latest
          format: table
          exit-code: '1'

      - name: Checkov IaC scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./deploy

      - name: License compliance
        uses: pilosus/action-pip-license-checker@v1
        with:
          requirements: requirements.txt

      - name: Secret detection
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml
          fail: true
